### ISSUE TITLE
higher version of fastdfs shows different type of value on total storage

### ISSUE THREAD

**Issue by Lionzj** [whithen/fastdfs-exporter#1]
higher version of fastdfs's fdfs_monitor output:

```
[root@hlet-fastdfs-tracker01 src]# fdfs_monitor /etc/fdfs/client.conf
server_count=1, server_index=0

tracker server is 10.1.99.34:22122

group count: 1

Group 1:
group name = group1
disk total space = 18,251,534 MB
disk free space = 18,251,251 MB
trunk free space = 0 MB
storage server count = 2
active server count = 2
storage server port = 23000
storage HTTP port = 8888
store path count = 1
subdir count per path = 256
current write server index = 1
current trunk file id = 0
```
need add a line before get the storage size:

`result = (re.sub(r'[^\w\s]', '', str(value)))`

# 数据格式化
def formatValue(value):
    try:
        # 匹配join time = 2019-04-04 17:00:49
        result = re.findall("(\d+-\d+-\d+ \d+:\d+:\d+)", value)
        if result:
            timeStamp = time.mktime(datetime.datetime.strptime(result[0], "%Y-%m-%d %H:%M:%S").timetuple())
            value = float(timeStamp)
        # 匹配total storage = 1007799 MB
        result = (re.sub(r'[^\w\s]', '', str(value)))		# 添加这一行
        result = re.findall("(\d+) MB$", result)
        if result: value = float(result[0]) * 1024 * 1024
        # 匹配ip_addr = 10.42.3.244  ACTIVE
        result = re.findall("(\d+\.\d+\.\d+\.\d+).+[A-Z]+", value)
        if result:
            if "ACTIVE" in value:
                value = 1
            else:
                value = 0
        # result = re.findall("(\d+)", value)
        # if result: value = float(value)
    except:
        raise
    finally:
        return value

**Comment by whithen** [comment]
已修改

**Comment by whithen** [comment]
已修改
